### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by LCAR979** [LCAR979/HPC_wiki_docs#4]
- [x] pycaffe
- [x] node2 和 node4 down掉的原因排查。 发现是网卡问题
- [x] tensorflow + horvord 安装 测试
- [ ] 报警 (+ 邮件？）尝试ganglia-monitor
- [x] 线程限制？
- [x] torch 出错。排查发现用的torch的modulefile路径有问题，导致walltime和runtime严重不匹配，runtime一直为1s
- [ ] qhold 无效
